version: '3.5'

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    volumes:
      - ./postgres:/data/postgres/
    ports:
      - "5432:5432"
